### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by szop85** [pkittenis/graphite-influxdb#6]
Hello,

I'm trying to install graphite-influxdb via pip install but I'm receiving following error:

```
root@mgm:~# pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
Cleaning up...
root@mgm:~# easy_install -U setuptools
Searching for setuptools
Reading https://pypi.python.org/simple/setuptools/
Best match: setuptools 18.3.1
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.zip#md5=c3b735ed07bd38e3145c165ac27b311f
Processing setuptools-18.3.1.zip
Writing /tmp/easy_install-U3XiR1/setuptools-18.3.1/setup.cfg
Running setuptools-18.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-U3XiR1/setuptools-18.3.1/egg-dist-tmp-hsEXPR
Moving setuptools-18.3.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding setuptools 18.3.1 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/setuptools-18.3.1-py2.7.egg
Processing dependencies for setuptools
Finished processing dependencies for setuptools

root@mgm:~# pip install https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
Downloading/unpacking https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
  Downloading 0.5.0-rc3.tar.gz
  Running setup.py (path:/tmp/pip-ysHtww-build/setup.py) egg_info for package from https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.5.0-rc3' to '0.5.0rc3'
      normalized_version,

Downloading/unpacking graphite-api (from graphite-influxdb==0.5.0rc3)
  Downloading graphite_api-1.0.1-py2.py3-none-any.whl (72kB): 72kB downloaded
Downloading/unpacking influxdb>=2.6.0 (from graphite-influxdb==0.5.0rc3)
  Downloading influxdb-2.9.1-py2.py3-none-any.whl (255kB): 255kB downloaded
Downloading/unpacking pytz (from graphite-api->graphite-influxdb==0.5.0rc3)
  Downloading pytz-2015.4-py2.py3-none-any.whl (475kB): 475kB downloaded
Downloading/unpacking Flask (from graphite-api->graphite-influxdb==0.5.0rc3)
  Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Flask/setup.py) egg_info for package Flask

    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking cairocffi (from graphite-api->graphite-influxdb==0.5.0rc3)
  Downloading cairocffi-0.7.2.tar.gz (75kB): 75kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cairocffi/setup.py) egg_info for package cairocffi
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cairocffi/setup.py", line 65, in <module>
        **cffi_args
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 638, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 851, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1067, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cairocffi/setup.py", line 65, in <module>

    **cffi_args

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 268, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 836, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in best_match

    return self.obtain(req, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1093, in obtain

    return installer(requirement)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 638, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 851, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1079, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1067, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cairocffi
Storing debug log for failure in /root/.pip/pip.log
```

Any idea?

Cheers,
David

**Comment by midse** [comment]
Python.h: No such file or directory

Maybe you're missing Python headers? Try to install the python-dev package.

**Comment by szop85** [comment]
Hello @midse,

stupid mistake because I was testing on a fresh machine. Sorry for bugging!

Cheers,
Szop
